name: Go Release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Go build
        run: |
          export GOARCH=amd64
          os_all='linux darwin windows'
          for os in $os_all; do
            CGO_ENABLED=0 GOOS=$os go build -ldflags '-w -s' -o release/word-$os-$GOARCH
          done
      - name: UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          file: release/*
          args: --best
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}